<a href="https://colab.research.google.com/github/Jen-Ocana/Fisica-Computacional-1/blob/master/Actividad3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad 3

In [74]:

import pandas as pd
import numpy as np
url= 'https://raw.githubusercontent.com/Jen-Ocana/Fisica-Computacional-1/master/Actividad%203/8352.txt'
my_cols = ['Fecha','Precip','Evap','Tmax','Tmin']

df_orig= pd.read_csv(url, names=my_cols, encoding='cp1251', sep='\s+', header=None, skiprows=19, skipfooter=1, engine='python')

################ARCHIVO ORIGINAL########################

#      al 20 sale todo y dos reglones de datos
#      reglon 18 o 19 contando el cero esta el primer dato
#      Reglon 17 vacio  18 contando el cero
#      primer numero/numero considerando el 0
#      Reglon 16/17 los nombres de las columnas no tienen la columan de fecha que
#      es la primera

##############INSTRUCCIONES DE LA ACTIVIDAD ##############
#Imprime el encabezado y final del dataframe: 
print("------Encabezado del dataframe---------- \n",df_orig.head(10))
print("")
print("------Final del dataframe---------- \n",df_orig.tail(10))
print("") 
#¿Qué dimensiones tiene tu dataframe?:
print("----------Dimensiones del data frame------\n",df_orig.shape,end="\n")
print("")
#¿Cómo es el contenido de tu dataframe?: \n
print("----------Informacion del data frame------\n")
print(df_orig.info(),end="\n")
print("")
#Los datos originales incluyen la cadena de caracteres 'Nulo', indicando que no 
#hubo datos para esa variable, ese día. Tenemos que reemplazar la palabra nulo 
#con la función: df.replace()
df_work0 = df_orig.copy()
df_work0.head()

str_Nulo = 'Nulo'
df_work1 = df_work0.replace(to_replace=str_Nulo, value='', regex=True)
df_work1.head()

print("--------Dataframe:Work1 info-------\n")
print(df_work1.info())
print("")

print("------Encabezado del dataframe nuevo--------- \n",df_work1.head())
print("")
#Después habrá que convertir a número flotante o numérico los datos de
# Precipitación, Evaporación, Temperatura Máxima y Temperatura mínima 
#utilizando la función: df.to_numeric()
#_________________________________________
## Deseamos convertir los valores de las variables ambientales a núm. flotantes 
cols_list = ['Precip', 'Evap', 'Tmax', 'Tmin']
for cols in cols_list:
  df_work1[cols] = pd.to_numeric(df_work1[cols], errors='coerce')

#Contrasta ahora la información de tu DataFrame con la función: df.info() 

print("------Informacion de la actualizacion---------\n")
print(df_work1.info()) 
##Aqui podemos ver arriba todavia que el tipo ya no son 5 objetos
print("")

#Se puede contabilizar el número de datos faltantes en esas variables mediante la función: df.isnull().sum()
# De la instrucción anterior, vemos que hay valores faltantes. Sumamos los valores nulos. 
print("------Sumando los valores nulos------\n")
print(df_work1.isnull().sum())
print("")

#Imprime de nuevo el encabezado y final de tu dataframe, con las funciones df.head() y df.tail()
print("------Encabezado del work1---------- \n",df_work1.head()) 
print("")
print("------Final del work1---------- \n",df_work1.tail())
print("")


#Realiza una estadística básica de las variables numéricas de tu dataframe
# usando la función: df.describe() y haz una interpretación de los resultados, 
#para ver si tienen sentido físico (por ej. valores negativos de precipitación, 
#valores extremos fuera de lo normal, etc)
print("------ Descripcion ---------- \n",df_work1.describe().round(2))
print("")
#Aqui todo parece tener sentido

------Encabezado del dataframe----------
         Fecha Precip  Evap  Tmax  Tmin
0  01/07/1983      0  Nulo  Nulo  Nulo
1  02/07/1983      0  Nulo  Nulo  Nulo
2  03/07/1983      0  Nulo    27  Nulo
3  04/07/1983      0  Nulo    29     9
4  05/07/1983      0  Nulo    31    12
5  06/07/1983      0  Nulo    30    16
6  07/07/1983      0  Nulo    27    20
7  08/07/1983      1  Nulo    31    17
8  09/07/1983      4  Nulo    37    18
9  10/07/1983      1  Nulo    32    17

------Final del dataframe----------
            Fecha Precip  Evap  Tmax Tmin
7897  21/11/2007      0  Nulo    23  4.2
7898  22/11/2007      0  Nulo    21    4
7899  23/11/2007   48.2  Nulo    21    3
7900  24/11/2007     14  Nulo    23    4
7901  25/11/2007      0  Nulo    21    3
7902  26/11/2007      0  Nulo    26    3
7903  27/11/2007      0  Nulo    22    4
7904  28/11/2007      0  Nulo    20    4
7905  29/11/2007     22  Nulo    24    3
7906  30/11/2007      0  Nulo  Nulo    3

----------Dimensiones del data frame------
 (7907, 5)

----------Informacion del data frame------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7907 non-null   object
 2   Evap    7907 non-null   object
 3   Tmax    7907 non-null   object
 4   Tmin    7907 non-null   object
dtypes: object(5)
memory usage: 309.0+ KB
None

--------Dataframe:Work1 info-------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7907 non-null   object
 2   Evap    7907 non-null   object
 3   Tmax    7907 non-null   object
 4   Tmin    7907 non-null   object
dtypes: object(5)
memory usage: 309.0+ KB
None

------Encabezado del dataframe nuevo---------
         Fecha Precip Evap Tmax Tmin
0  01/07/1983      0
1  02/07/1983      0
2  03/07/1983      0        27
3  04/07/1983      0        29    9
4  05/07/1983      0        31   12

------Informacion de la actualizacion---------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7783 non-null   float64
 2   Evap    0 non-null      float64
 3   Tmax    7815 non-null   float64
 4   Tmin    7819 non-null   float64
dtypes: float64(4), object(1)
memory usage: 309.0+ KB
None

------Sumando los valores nulos------

Fecha        0
Precip     124
Evap      7907
Tmax        92
Tmin        88
dtype: int64

------Encabezado del work1----------
         Fecha  Precip  Evap  Tmax  Tmin
0  01/07/1983     0.0   NaN   NaN   NaN
1  02/07/1983     0.0   NaN   NaN   NaN
2  03/07/1983     0.0   NaN  27.0   NaN
3  04/07/1983     0.0   NaN  29.0   9.0
4  05/07/1983     0.0   NaN  31.0  12.0

------Final del work1----------
            Fecha  Precip  Evap  Tmax  Tmin
7902  26/11/2007     0.0   NaN  26.0   3.0
7903  27/11/2007     0.0   NaN  22.0   4.0
7904  28/11/2007     0.0   NaN  20.0   4.0
7905  29/11/2007    22.0   NaN  24.0   3.0
7906  30/11/2007     0.0   NaN   NaN   3.0

------ Descripcion ----------
         Precip  Evap     Tmax     Tmin
count  7783.00   0.0  7815.00  7819.00
mean      3.35   NaN    23.88     6.60
std       9.08   NaN     5.41     5.29
min       0.00   NaN     4.00   -13.00
25%       0.00   NaN    20.50     4.00
50%       0.00   NaN    24.00     7.00
75%       0.00   NaN    27.00    10.00
max     103.00   NaN    41.00    22.00