#Actividad 3
En esta actividad trabajamos con los datos de la estacion climatologica de Basaseachi, Chihuahua.

In [1]:

import pandas as pd
import numpy as np
url= 'https://raw.githubusercontent.com/Jen-Ocana/Fisica-Computacional-1/master/Actividad%203/8352.txt'
my_cols = ['Fecha','Precip','Evap','Tmax','Tmin']

df_orig= pd.read_csv(url, names=my_cols, encoding='cp1251', sep='\s+', header=None, skiprows=19, skipfooter=1, engine='python')

################ARCHIVO ORIGINAL########################

#      al 20 sale todo y dos reglones de datos
#      reglon 18 o 19 contando el cero esta el primer dato
#      Reglon 17 vacio  18 contando el cero
#      primer numero/numero considerando el 0
#      Reglon 16/17 los nombres de las columnas no tienen la columan de fecha que
#      es la primera

##############INSTRUCCIONES DE LA ACTIVIDAD ##############
#Imprime el encabezado y final del dataframe: 
print("------Encabezado del dataframe---------- \n",df_orig.head(10))
print("")
print("------Final del dataframe---------- \n",df_orig.tail(10))
print("") 
#¿Qué dimensiones tiene tu dataframe?:
print("----------Dimensiones del data frame------\n",df_orig.shape,end="\n")
print("")
#¿Cómo es el contenido de tu dataframe?: \n
print("----------Informacion del data frame------\n")
print(df_orig.info(),end="\n")
print("")
#Los datos originales incluyen la cadena de caracteres 'Nulo', indicando que no 
#hubo datos para esa variable, ese día. Tenemos que reemplazar la palabra nulo 
#con la función: df.replace()
df_work0 = df_orig.copy()
df_work0.head()

str_Nulo = 'Nulo'
df_work1 = df_work0.replace(to_replace=str_Nulo, value='', regex=True)
df_work1.head()

print("--------Dataframe:Work1 info-------\n")
print(df_work1.info())
print("")

print("------Encabezado del dataframe nuevo--------- \n",df_work1.head())
print("")
#Después habrá que convertir a número flotante o numérico los datos de
# Precipitación, Evaporación, Temperatura Máxima y Temperatura mínima 
#utilizando la función: df.to_numeric()
#_________________________________________
## Deseamos convertir los valores de las variables ambientales a núm. flotantes 
cols_list = ['Precip', 'Evap', 'Tmax', 'Tmin']
for cols in cols_list:
  df_work1[cols] = pd.to_numeric(df_work1[cols], errors='coerce')

#Contrasta ahora la información de tu DataFrame con la función: df.info() 

print("------Informacion de la actualizacion---------\n")
print(df_work1.info()) 
##Aqui podemos ver arriba todavia que el tipo ya no son 5 objetos
print("")

#Se puede contabilizar el número de datos faltantes en esas variables mediante la función: df.isnull().sum()
# De la instrucción anterior, vemos que hay valores faltantes. Sumamos los valores nulos. 
print("------Sumando los valores nulos------\n")
print(df_work1.isnull().sum())
print("")

#Imprime de nuevo el encabezado y final de tu dataframe, con las funciones df.head() y df.tail()
print("------Encabezado del work1---------- \n",df_work1.head()) 
print("")
print("------Final del work1---------- \n",df_work1.tail())
print("")


#Realiza una estadística básica de las variables numéricas de tu dataframe
# usando la función: df.describe() y haz una interpretación de los resultados, 
#para ver si tienen sentido físico (por ej. valores negativos de precipitación, 
#valores extremos fuera de lo normal, etc)
print("------ Descripcion ---------- \n",df_work1.describe().round(2))
print("")
#Aqui todo parece tener sentido


##########---Hacemos work2 para modificar la fecha----######
###Escribimos las instrucciones del paso 4

print("###########PASO 4 MODIFICANDO LA FECHA############")
print("")

#Comienza haciendo una copia del dataframe del paso anterior
#, por si se requiere recuperar el nuevo dataframe,
# utilizando df:new=df.copy()

df_work2=df_work1.copy()
print("Vemos la columan de fecha solamente \n")
print(df_work2['Fecha'].head())
print("")

#Utiliza la función de Pandas pd.to_datetime(), 
#para convertir el objeto Fecha a formato de fecha 
#que comprende Python.  Lee el manual de esa función e 
#intenta la conversión. 
#df_work2['Fecha']=pd.to_datetime(df_work2['fecha'],dayfirst=True).copy()
df_work2['Fecha']=pd.to_datetime(df_work2['Fecha'], dayfirst=True).copy()
print("------ Encabezado correjida la fecha ---------- \n")
print("")
print(df_work2.head())
print("------- Encabezado del work2 ----------\n")
print(df_work1.head())
##Para comparar
print("")

#Después utiliza la función df.dtypes para verificar que todas 
#las variables son del tipo deseado. 
print("------ Checando tipos de la fecha ---------- \n")
print(df_work2.dtypes)
print("")

#Enseguida con la ayuda de las funciones de 
#Pandas df['Fecha'].dt.year y df['Fecha'].dt.month, crea 
#dos columnas nuevas adicionales df['Año'] y df['Mes'].
df_work2['Año'] = df_work2['Fecha'].dt.year
df_work2['Mes'] = df_work2['Fecha'].dt.month

#Utilizando la función print aplicado a las funciones 
#df.head() y df.tail(), verifica que el dataframe tiene 
#la forma deseada.
print("------------Encabezado con las columnas de año---------\n")
print(df_work2.head())
print("")
print("------------Final con las columnas de año-------------\n")
print(df_work2.tail())
print("")

#Y complementa con la función df.dtypes, para verificar que todas
# las variables son del tipo adecuado. 
print("----Comprobamos que todas las variables sean del tipo deseado-----")
print("")
print(df_work2.info())
print("")
print("***********Terminamos*************")

#Hasta aquí llegaremos esta semana.

------Encabezado del dataframe----------
         Fecha Precip  Evap  Tmax  Tmin
0  01/07/1983      0  Nulo  Nulo  Nulo
1  02/07/1983      0  Nulo  Nulo  Nulo
2  03/07/1983      0  Nulo    27  Nulo
3  04/07/1983      0  Nulo    29     9
4  05/07/1983      0  Nulo    31    12
5  06/07/1983      0  Nulo    30    16
6  07/07/1983      0  Nulo    27    20
7  08/07/1983      1  Nulo    31    17
8  09/07/1983      4  Nulo    37    18
9  10/07/1983      1  Nulo    32    17

------Final del dataframe----------
            Fecha Precip  Evap  Tmax Tmin
7897  21/11/2007      0  Nulo    23  4.2
7898  22/11/2007      0  Nulo    21    4
7899  23/11/2007   48.2  Nulo    21    3
7900  24/11/2007     14  Nulo    23    4
7901  25/11/2007      0  Nulo    21    3
7902  26/11/2007      0  Nulo    26    3
7903  27/11/2007      0  Nulo    22    4
7904  28/11/2007      0  Nulo    20    4
7905  29/11/2007     22  Nulo    24    3
7906  30/11/2007      0  Nulo  Nulo    3

----------Dimensiones del data frame------
 (7907, 5)

----------Informacion del data frame------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7907 non-null   object
 2   Evap    7907 non-null   object
 3   Tmax    7907 non-null   object
 4   Tmin    7907 non-null   object
dtypes: object(5)
memory usage: 309.0+ KB
None

--------Dataframe:Work1 info-------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7907 non-null   object
 2   Evap    7907 non-null   object
 3   Tmax    7907 non-null   object
 4   Tmin    7907 non-null   object
dtypes: object(5)
memory usage: 309.0+ KB
None

------Encabezado del dataframe nuevo---------
         Fecha Precip Evap Tmax Tmin
0  01/07/1983      0
1  02/07/1983      0
2  03/07/1983      0        27
3  04/07/1983      0        29    9
4  05/07/1983      0        31   12

------Informacion de la actualizacion---------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   object
 1   Precip  7783 non-null   float64
 2   Evap    0 non-null      float64
 3   Tmax    7815 non-null   float64
 4   Tmin    7819 non-null   float64
dtypes: float64(4), object(1)
memory usage: 309.0+ KB
None

------Sumando los valores nulos------

Fecha        0
Precip     124
Evap      7907
Tmax        92
Tmin        88
dtype: int64

------Encabezado del work1----------
         Fecha  Precip  Evap  Tmax  Tmin
0  01/07/1983     0.0   NaN   NaN   NaN
1  02/07/1983     0.0   NaN   NaN   NaN
2  03/07/1983     0.0   NaN  27.0   NaN
3  04/07/1983     0.0   NaN  29.0   9.0
4  05/07/1983     0.0   NaN  31.0  12.0

------Final del work1----------
            Fecha  Precip  Evap  Tmax  Tmin
7902  26/11/2007     0.0   NaN  26.0   3.0
7903  27/11/2007     0.0   NaN  22.0   4.0
7904  28/11/2007     0.0   NaN  20.0   4.0
7905  29/11/2007    22.0   NaN  24.0   3.0
7906  30/11/2007     0.0   NaN   NaN   3.0

------ Descripcion ----------
         Precip  Evap     Tmax     Tmin
count  7783.00   0.0  7815.00  7819.00
mean      3.35   NaN    23.88     6.60
std       9.08   NaN     5.41     5.29
min       0.00   NaN     4.00   -13.00
25%       0.00   NaN    20.50     4.00
50%       0.00   NaN    24.00     7.00
75%       0.00   NaN    27.00    10.00
max     103.00   NaN    41.00    22.00

###########PASO 4 MODIFICANDO LA FECHA############

Vemos la columan de fecha solamente

0    01/07/1983
1    02/07/1983
2    03/07/1983
3    04/07/1983
4    05/07/1983
Name: Fecha, dtype: object

------ Encabezado correjida la fecha ----------


       Fecha  Precip  Evap  Tmax  Tmin
0 1983-07-01     0.0   NaN   NaN   NaN
1 1983-07-02     0.0   NaN   NaN   NaN
2 1983-07-03     0.0   NaN  27.0   NaN
3 1983-07-04     0.0   NaN  29.0   9.0
4 1983-07-05     0.0   NaN  31.0  12.0
------- Encabezado del work2 ----------

        Fecha  Precip  Evap  Tmax  Tmin
0  01/07/1983     0.0   NaN   NaN   NaN
1  02/07/1983     0.0   NaN   NaN   NaN
2  03/07/1983     0.0   NaN  27.0   NaN
3  04/07/1983     0.0   NaN  29.0   9.0
4  05/07/1983     0.0   NaN  31.0  12.0

------ Checando tipos de la fecha ----------

Fecha     datetime64[ns]
Precip           float64
Evap             float64
Tmax             float64
Tmin             float64
dtype: object

------------Encabezado con las columnas de año---------

       Fecha  Precip  Evap  Tmax  Tmin   Año  Mes
0 1983-07-01     0.0   NaN   NaN   NaN  1983    7
1 1983-07-02     0.0   NaN   NaN   NaN  1983    7
2 1983-07-03     0.0   NaN  27.0   NaN  1983    7
3 1983-07-04     0.0   NaN  29.0   9.0  1983    7
4 1983-07-05     0.0   NaN  31.0  12.0  1983    7

------------Final con las columnas de año-------------

          Fecha  Precip  Evap  Tmax  Tmin   Año  Mes
7902 2007-11-26     0.0   NaN  26.0   3.0  2007   11
7903 2007-11-27     0.0   NaN  22.0   4.0  2007   11
7904 2007-11-28     0.0   NaN  20.0   4.0  2007   11
7905 2007-11-29    22.0   NaN  24.0   3.0  2007   11
7906 2007-11-30     0.0   NaN   NaN   3.0  2007   11

----Comprobamos que todas las variables sean del tipo deseado-----

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   7907 non-null   datetime64[ns]
 1   Precip  7783 non-null   float64
 2   Evap    0 non-null      float64
 3   Tmax    7815 non-null   float64
 4   Tmin    7819 non-null   float64
 5   Año     7907 non-null   int64
 6   Mes     7907 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(2)
memory usage: 432.5 KB
None

***********Terminamos*************